### ISSUE TITLE
Question - 

### ISSUE THREAD

**Issue by kholyphoenix1** [jonata/opendvdproducer#11]
Hello, 

1° Problem - You can only generate ISO when the application runs as an administrator in Windows. Still a bug with "mkisofs.exe".
2° Problem - The App creates a file with the name of 'DVD.odvdp' with size equal to 0kb.

Can someone help me?
Thank you!

Can someone help me?
Thank you! #

**Comment by xpaneitor** [comment]
the DVD.odvdp file is the saved project file, so that you can reopen, at least thats what I notice on my computer, I think that are only links to the files you are using, thats why is so small.

**Comment by kholyphoenix1** [comment]
Thanks a lot!
