### ISSUE TITLE
vertical scrolling

### ISSUE THREAD

**Issue by markybob** [jonata/opendvdproducer#13]
i can't see all of the options as they get cut off since my monitor isn't large enough and there are no scrollbars to access them.  in this example see "GOP Size" and "Audio Data Rate" being cut off. 

![screenshot_2016-11-09_08-24-11](https://cloud.githubusercontent.com/assets/212093/20141455/0a4bbdda-a656-11e6-87fb-81ae1e803d81.png)

**Comment by jonata** [comment]
Good point. I will fix that in other areas of the interface too.

**Comment by jonata** [comment]
Hi all

I am moving the development to GitLab and hopefully will update the software. See you there!
https://gitlab.com/jonata/opendvdproducer

Thanks for your attention.
