### ISSUE TITLE
External process return code not validated

### ISSUE THREAD

**Issue by matthew11** [jonata/opendvdproducer#14]
The title is pretty self-explaining. OpenDVDProducer do some external process call, however it is rarely checked whether the command was executed successfully.

Either the return code should be checked, or maybe a better approach is to use the check_call() of the subprocess which throws an exception upon non-zero return code, and the exception can be handled properly.

Currently if something fails I only encounter a zero-sized ISO file without any error message shown. (only the terminal log - if started from there - gives some evidence about the problem)

**Comment by jonata** [comment]
Hi all

I am moving the development to GitLab and hopefully will update the software. See you there!
https://gitlab.com/jonata/opendvdproducer

Thanks for your attention.
