### ISSUE TITLE
Saved projects are empty (0kb) on Windows 10

### ISSUE THREAD

**Issue by edwardbuck** [jonata/opendvdproducer#17]
Hello,
I have downloaded and installed the Windows version from your site (opendvdproducer.jonata.org).  I have added a few videos, created a menu, but when I save the project, the "saved" file is 0kb.  The odvdp file is empty.  I have tried running the program as administrator, but it makes no difference.

I also have another issue where mkisofs.exe crashes everytime it starts to make the iso, so I'm unable to actually get a finished product.

I am running on Windows 10.  Also, I am running ver 16.11.
Thanks!

**Comment by jonata** [comment]
Hi all

I am moving the development to GitLab and hopefully will update the software. See you there!
https://gitlab.com/jonata/opendvdproducer

Thanks for your attention.
