### ISSUE TITLE
Windows 10 mkisofs.exe stoppping during or after running ffmpeg.exe

### ISSUE THREAD

**Issue by Ally447** [jonata/opendvdproducer#18]
Above says it all, but as the user interface is quite user-unfriendly and I only got the program to generate an ISO by (almost) random clicking, I'm not even sure I did everything necessary or correctly.

**Comment by jonata** [comment]
Hi all

I am moving the development to GitLab and hopefully will update the software. See you there!
https://gitlab.com/jonata/opendvdproducer

Thanks for your attention.
