### ISSUE TITLE
trying to install on Ubuntu 14.04

### ISSUE THREAD

**Issue by smfabac** [jonata/opendvdproducer#19]
I've followed instructions on installing .deb packages on ubuntu 14.04 with gdebi package installer but the install fails with the message: "Dependency is not satisfiable ffmpeg"  How do I get past this error?

**Comment by jonata** [comment]
Hi all

I am moving the development to GitLab and hopefully will update the software. See you there!
https://gitlab.com/jonata/opendvdproducer

Thanks for your attention.
