### ISSUE TITLE
I made and ISO on windows but menu dont work

### ISSUE THREAD

**Issue by guarendick** [jonata/opendvdproducer#2]
I think this is a great project if you consider that the unique cross platform authoring DVD software is Adobe Encore, but is rubbish.

If you write some kind of tutorial or make any kind of explain video, specially for the menu process, it would be great. I can help you if you want it. I live in Chile and work in a cross platform production environment, and we really need and alternative to Encore who work on Mac and Windows, because despite what video industry think we still need DVD discs.

**Comment by jonata** [comment]
Hi guarendick

Sorry by the late in reply. As I said in issue #1, we are developing this software mainly in Linux and Mac platforms, and the Windows version is not our primary focus. Anyway, I will take a look at this in the following days and hopefuly we will have a more stable version for Windows.

Thanks for your attention.

**Comment by jonata** [comment]
Hi guarandick

Please, what audio format did you use for your project? I see that the only one (and it seems to be the default on commercial DVDs) that actually run well on players are AC3. I will investigate about PCM (it is on the DVD specification, but as I said it seems that the industry uses AC3).

Thanks for your attention.

**Comment by guarendick** [comment]
The most widely audio format in DVD is MPEG-1 Layer 2 audio.
PCM is too heave and result in more large size files.

**Comment by MikoPi** [comment]
It is possible to have 5.1 dolby sound with odvdp?

**Comment by jonata** [comment]
Probably, but not using the odvdp encoder. #5
