### ISSUE TITLE
Create DVD

### ISSUE THREAD

**Issue by SuriyaaKudoIsc** [jonata/opendvdproducer#20]
@jonata How can I export an existing project to a DVD?

Not all functions can be displayed (see bottom of the program):

![screenshot 2017-09-09 12 56 58](https://user-images.githubusercontent.com/5073946/30239538-e169a0aa-955e-11e7-89d7-8b647ac39089.png)

**Comment by xpaneitor** [comment]
That might be only changing your screen resolution. i hope so

<img width="1540" alt="captura de pantalla 2018-02-12 a la s 18 58 02" src="https://user-images.githubusercontent.com/36427740/36128193-b2db7b94-1026-11e8-9a3b-59b4c8063153.png">
