### ISSUE TITLE
Any documentation?

### ISSUE THREAD

**Issue by mareeba** [jonata/opendvdproducer#21]
Looks like a great app but extremely broken UI on OSX 10.11.6.

Is there any documentation anywhere? Tutorials etc.?

**Comment by ed65love** [comment]
Yes please, it's currrently very pretty, but unusable. How are users supposed to use it?!

**Comment by AALMA** [comment]
same here, I'm trying to see if I can figure it out by reading the saved .odvp file and just manually edit that ¯\_(ツ)_/¯

**Comment by jonata** [comment]
Hi all

I am moving the development to GitLab and hopefully will update the software. See you there!
https://gitlab.com/jonata/opendvdproducer

Thanks for your attention.
