### ISSUE TITLE
Generated iso file has size 0 on windows

### ISSUE THREAD

**Issue by kolbma** [jonata/opendvdproducer#23]
I'm using latest windows version and the generated iso file is empty.
No error message.

Not sure if it is related to #11 or #18

**Comment by xpaneitor** [comment]
that happens to me, but I use the reencode option and works

**Comment by jonata** [comment]
Hi all

I am moving the development to GitLab and hopefully will update the software. See you there!
https://gitlab.com/jonata/opendvdproducer

Thanks for your attention.
