### ISSUE TITLE
Awesome but a few suggestions

### ISSUE THREAD

**Issue by xpaneitor** [jonata/opendvdproducer#24]
Awesome peace of software, it made me don't miss adobe encore on my Mac anymore, it has almost anything that I need, but here are some suggestions (that are only that...suggestions.  👍)

1. I manage to understand how it works, but it would be pretty useful if it has guide on how to

2. don't now how is called, but would be nice if you add those pop ups that merge when u are above an icon and describes what those it do

3. when you get to add marks to a video, the UI get bugged cause there is no way to quit that option and get back to the menu when you can select if you want to reencode the video

4. Please fix the compatibility whit .m4v so there is no need to reencode everything (at least on my workflow)

5. I see that you are working on fixing the buttons workflow, so excited about that, tanks

6. A way to automatically transform all of my clips into a chapter would be very useful

7.  So please improve the adding marks and chapter options cause is a bit hard to be very precise

8. there are some other minor UI bugs, but I don't care about those cause maybe those are only uncomfortables for me and my workflow.

9. Would love to see blu-ray compatibility 

Even if nothing of this list was implemented, **this program is definitely my new DVD authoring program**, cause is so good, simple and way to fast (for me it eliminated the need to transport my data to a PC and work on adobe encore). even so, it is so easy to use once that you figure it out.

So many thanks and I hope to see future updates ;)

<img width="745" alt="captura de pantalla 2018-02-12 a la s 18 52 04" src="https://user-images.githubusercontent.com/36427740/36128047-dedde16a-1025-11e8-9d30-8ff3cda02ffc.png">

**Comment by jonata** [comment]
Hi all

I am moving the development to GitLab and hopefully will update the software. See you there!
https://gitlab.com/jonata/opendvdproducer

Thanks for your attention.
