### ISSUE TITLE
Question about dependencies and building from source

### ISSUE THREAD

**Issue by youknowwho** [jonata/opendvdproducer#3]
Hello:

First, many thanks to the people developing and working on this project. This looks like a very exciting project, and my hat is off to those who are working on it.

I did have a couple of questions.

First, what are the dependencies? I noticed that I should probably have PySide. Are there others?

Second, how do you build the software from source, and after it is built, how do you execute the software?

Looking at the source, it seems like it's coded in Python. For most Python packages, I would execute something similar to the following:

```
python2 setup.py build
python2 setup.py install --prefix=/usr
```

This seems to work fine, except for the following warning:

```
/usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'app'
  warnings.warn(msg)
running build
```

After executing the install command, it seems to install, but I don't see where the executables have been copied, and I don't know how to start the program.

I do see the following was copied to /usr/lib/python2.7/site-packages/

Open_DVD_Producer-15.11-py2.7.egg

But I don't see a way to start the program. If I try starting it while it's in place (entering the top-level of the source code directory, and manually entering "python2 ./opendvdproducer.py" [without the quotes]), it produces this output:

```
0
Traceback (most recent call last):
  File "./opendvdproducer.py", line 3685, in <module>
    app.main = main_window()
  File "./opendvdproducer.py", line 1988, in __init__
    clean_changes(self)
  File "./opendvdproducer.py", line 2297, in clean_changes
    nowediting_panel_button_changed(self, self.nowediting)
  File "./opendvdproducer.py", line 2153, in nowediting_panel_button_changed
    clean_menus_list_selection(self)
  File "./opendvdproducer.py", line 3176, in clean_menus_list_selection
    self.nowediting_menus_panel_duplicate.setEnabled()
TypeError: setEnabled() takes exactly one argument (0 given)
```

So I am thinking that perhaps I am not entering the command correctly, or perhaps I am missing other dependencies or Python modules that are needed. As it turns out, I am not a developer and know a little bit about Python, but not enough to determine what's gone wrong here.

I am doing this on a Gentoo GNU/Linux system. I am really interested in trying the program, so I  would definitely appreciate any ideas about how to get it working.

Thank you so much for your thoughts on this.

Best Regards,

YKW

**Comment by jonata** [comment]
Hi YKW

Thanks for your comments about the project. 

Well, it is not designed (at least by now) to be a python package. So in this case, probably it will not install into the python package system.

To run it on a linux system you need to have PySide (more specifically, PySide QtGui, PySide QtCore and PySide Phonon). With this you should have the interface running.

Then, you need to have the ImageMagick binaries to manipulate images and ffmpeg to manipulate videos. 

Then, you need dvdauthor, and mkisofs to generate the ISO files.

This last one is "polemic", because there are many options out there to generate ISO files, but I am using the original last version from the project cdrtools.

I think that is it. Please let me know if you get it running in Gentoo.

**Comment by youknowwho** [comment]
Hello Jonata,

Thank you so much for getting back to me. My apologies for not checking back in earlier today. I will certainly keep you posted when I am able to get Open DVD Producer on Gentoo GNU/Linux.

I have checked the list of dependencies that you outlined, and I can verify that I think that I have most of them, if not all.

I don't know if Gentoo's package manager specifically includes "PySide QtGui", "PySide QtCore" and "PySide Phonon", but I could certainly check into this if you think that Gentoo's PySide package might not cover the "QtGui", "QtCore", and "Phonon" dependencies. I went ahead and installed "dev-python/pyside-tools" package, just in case. So, to confirm, I have the following packages installed:

```
emerge --search pyside
*  dev-python/pyside
      Latest version available: 1.2.2-r1
      Latest version installed: 1.2.2-r1
      Size of files: 3678 KiB
      Homepage:      http://qt-project.org/wiki/PySide
      Description:   Python bindings for the Qt framework
      License:       LGPL-2.1

*  dev-python/pyside-tools
      Latest version available: 0.2.15-r1
      Latest version installed: 0.2.15-r1
      Size of files: 78 KiB
      Homepage:      https://wiki.qt.io/Pyside
      Description:   PySide development tools (lupdate, rcc, uic)
      License:       BSD GPL-2

```

I can assure you that I have Imagemagick. I have used it for years; it is a wonderful set of programs that has proven useful and saved me so much time that it's not funny. It's a must-have for me. It's installed:

```
*  media-gfx/imagemagick
      Latest version available: 6.9.0.3
      Latest version installed: 6.9.0.3
      Size of files: 7714 KiB
      Homepage:      http://www.imagemagick.org/
      Description:   A collection of tools and libraries for many image formats
      License:       imagemagick
```

I also have dvdauthor:


```
*  media-video/dvdauthor
      Latest version available: 0.7.1
      Latest version installed: 0.7.1
      Size of files: 412 KiB
      Homepage:      http://dvdauthor.sourceforge.net/
      Description:   Tools for generating DVD files to be played on standalone DVD players
      License:       GPL-2
```


```
dvdauthor --version
DVDAuthor::dvdauthor, version 0.7.1.
Build options: gnugetopt imagemagick iconv freetype fribidi fontconfig
Send bug reports to <dvdauthor-users@lists.sourceforge.net>

INFO: no default video format, must explicitly specify NTSC or PAL
dvdauthor: unrecognized option '--version'
ERR:  getopt returned bad code 63
```

I also prefer using mkisofs exclusively from the cdrtools software developed by Jörg Schilling [http://cdrtools.sourceforge.net/private/cdrecord.html]. I go to great lengths to ensure that this is used instead of anything else.

```
*  app-cdr/cdrtools
      Latest version available: 3.01_alpha17
      Latest version installed: 3.01_alpha17
      Size of files: 2014 KiB
      Homepage:      http://sourceforge.net/projects/cdrtools/
      Description:   A set of tools for CD/DVD reading and recording, including cdrecord
      License:       GPL-2 LGPL-2.1 CDDL-Schily

*  virtual/cdrtools
      Latest version available: 0
      Latest version installed: 0
      Size of files: 0 KiB
      Homepage:      
      Description:   Virtual for command-line recorders cdrtools and cdrkit
      License:       
```

Executing cdrecord and mkisofs on the command line would produce the following outputs:


```
cdrecord --version 
Cdrecord-ProDVD-ProBD-Clone 3.01a16 (x86_64-unknown-linux-gnu) Copyright (C) 1995-2013 Joerg Schilling
```


```
mkisofs --version
mkisofs 3.01a16 (x86_64-unknown-linux-gnu) Copyright (C) 1993-1997 Eric Youngdale (C) 1997-2013 Joerg Schilling
```

Also, I have certainly sworn by ffmpeg. It's also a great program that world couldn't do without:


```
*  media-video/ffmpeg
      Latest version available: 2.6.3
      Latest version installed: 2.6.3
      Size of files: 7621 KiB
      Homepage:      http://ffmpeg.org/
      Description:   Complete solution to record, convert and stream audio and video. Includes libavcodec
      License:       !gpl? ( LGPL-2.1 ) gpl? ( GPL-2 ) amr? ( gpl? ( GPL-3 ) !gpl? ( LGPL-3 ) ) encode? ( aac? ( gpl? ( GPL-3 ) !gpl? ( LGPL-3 ) ) amrenc? ( gpl? ( GPL-3 ) !gpl? ( LGPL-3 ) ) ) samba? ( GPL-3 )
```


```
ffmpeg --version
ffmpeg version 2.6.3 Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 4.9.3 (Gentoo 4.9.3 p1.3, pie-0.6.3)
```


So I did try running it as a standard user, and I noticed that the following error message is displayed:



```
python opendvdproducer.py 
  File "opendvdproducer.py", line 373
    print sound_length_xml
                         ^
SyntaxError: Missing parentheses in call to 'print'
```


But if I try to use python2, the following error is displayed:

```
python2 opendvdproducer.py 
0
Traceback (most recent call last):
  File "opendvdproducer.py", line 3685, in <module>
    app.main = main_window()
  File "opendvdproducer.py", line 1988, in __init__
    clean_changes(self)
  File "opendvdproducer.py", line 2297, in clean_changes
    nowediting_panel_button_changed(self, self.nowediting)
  File "opendvdproducer.py", line 2153, in nowediting_panel_button_changed
    clean_menus_list_selection(self)
  File "opendvdproducer.py", line 3176, in clean_menus_list_selection
    self.nowediting_menus_panel_duplicate.setEnabled()
TypeError: setEnabled() takes exactly one argument (0 given)
```

Should I be using python2 or python3?

Your ideas and thoughts are much appreciated. I would definitely like to see what the software if capable of doing with my home DVDs. Thank you so much again for developing this project!!

Best Regards,


YKW

**Comment by jonata** [comment]
Sorry by the late

I think you can test from the actual version (not the release). I have cleaned up the code so this kind of silly bug should be out.

Try with the actual code, please.

Thanks for your attention.

**Comment by jonata** [comment]
Hi there

Could you try with the last release (16.02) ?

Thanks!

**Comment by jonata** [comment]
Hello YKW

Could you tell me if your building process is going right?

If yes, can I close this issue?

Thanks for your attention!

**Comment by jonata** [comment]
Hi all

I am moving the development to GitLab and hopefully will update the software. See you there!
https://gitlab.com/jonata/opendvdproducer

Thanks for your attention.
