### ISSUE TITLE
5.1 dolby sound

### ISSUE THREAD

**Issue by MikoPi** [jonata/opendvdproducer#5]
Can I use somehow 5.1 dolby sound with my dvd?

**Comment by jonata** [comment]
Yes, but you need to convert it outside Open DVD Producer, with the "ac3" codec, and check the video to not be reencoded.

**Comment by MikoPi** [comment]
Looks like it works even with ODP converting from mp4 to ac3 - 5.1 dolby is still there.

**Comment by jonata** [comment]
Hi MikoPi

Yes, if you select "AC3" as sound format for your DVD, the converter tool will take care of the 5.1 audio.

Thanks for your attention.
