### ISSUE TITLE
./silence.flac: No such file or directory

### ISSUE THREAD

**Issue by brunetton** [jonata/opendvdproducer#8]
Hi

Just discovered opendvdproducer and I'm happy to discover it. I really appreciate the way it's designed: using external tools for menus images generation, and focus to essential: DVD authorizing.
I really appreciate the "overlay preview" option, this is a great idea, missing in all other softs.

Today I wanted to generate a simple DVD with only one menu, one button, and one video. But the menu mpg was not created. In logs:

```
Input #0, png_pipe, from '/home/bruno/boulots/DVD test/exemple menu - fond.png':
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: png, rgba(pc), 889x500 [SAR 5625:5625 DAR 889:500], 25 fps, 25 tbr, 25 tbn, 25 tbc
./silence.flac: No such file or directory
Traceback (most recent call last):
  File "./opendvdproducer.py", line 572, in run
    menu_mpg_file = open(os.path.join(path_tmp, menu + '.mpg'))
IOError: [Errno 2] Aucun fichier ou dossier de ce type: u'/tmp/opendvdproducer-8749/exemple menu - fond.mpg'
```

**Comment by jonata** [comment]
Thanks a lot!!

**Comment by brunetton** [comment]
My pleasure ;)
I don't think this will be my last and unique contribution !

2016-09-14 23:44 GMT+02:00 Jonatã Bolzan <notifications@github.com>:
